This is makeindex, version 2.15 [TeX Live 2020] (kpathsea + Thai support).
Scanning style file ./Glossary.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Glossary.acn....done (5 entries accepted, 0 rejected).
Sorting entries....done (12 comparisons).
Generating output file Glossary.acr....done (18 lines written, 0 warnings).
Output written in Glossary.acr.
Transcript written in Glossary.alg.
